//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    [System.Data.Services.Common.DataServiceEntity]
    [System.Data.Services.Common.DataServiceKey("UserId", "ContactNumberId")]
    public partial class ContactNumber : System.IEquatable<ContactNumber>
    {
        public System.Guid UserId { get; set; }
        public System.Guid ContactNumberId { get; set; }
        public string Number { get; set; }
        public string Extension { get; set; }
        public int Type { get; set; }
    
        public virtual User User { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is ContactNumber ? Equals(obj as ContactNumber) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ UserId.GetHashCode();
    			hash = (hash * 16777619) ^ ContactNumberId.GetHashCode();
    			hash = (hash * 16777619) ^ (Number == null ? 0 : Number.GetHashCode());
    			hash = (hash * 16777619) ^ (Extension == null ? 0 : Extension.GetHashCode());
    			hash = (hash * 16777619) ^ Type.GetHashCode();
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<ContactNumber> Members
    
    	public bool Equals(ContactNumber rhs)
    	{
    		if(rhs == null)
    			return false;
    			
    		return System.Collections.Generic.EqualityComparer<ContactNumber>.Equals(UserId, rhs.UserId) && System.Collections.Generic.EqualityComparer<ContactNumber>.Equals(ContactNumberId, rhs.ContactNumberId) && System.Collections.Generic.EqualityComparer<ContactNumber>.Equals(Number, rhs.Number) && System.Collections.Generic.EqualityComparer<ContactNumber>.Equals(Extension, rhs.Extension) && System.Collections.Generic.EqualityComparer<ContactNumber>.Equals(Type, rhs.Type);
    	}
    
    	#endregion
    }
}
