//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    [System.Data.Services.Common.DataServiceEntity]
    [System.Data.Services.Common.DataServiceKey("FileKey")]
    public partial class FilesFileData : System.IEquatable<FilesFileData>
    {
        public System.Guid FileKey { get; set; }
        public byte[] FileData { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is FilesFileData ? Equals(obj as FilesFileData) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ FileKey.GetHashCode();
    			if(FileData == null) { hash = (hash * 16777619) ^ 0; } else { foreach( byte b in FileData ) { hash = (hash * 16777619) ^ b.GetHashCode(); } }
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<FilesFileData> Members
    
    	public bool Equals(FilesFileData rhs)
    	{
    		if(rhs == null)
    			return false;
    			
    		return System.Collections.Generic.EqualityComparer<FilesFileData>.Equals(FileKey, rhs.FileKey) && ((FileData == null && rhs.FileData == null) ? true : (FileData == null || rhs.FileData == null) ? false : System.Linq.Enumerable.SequenceEqual(FileData, rhs.FileData));
    	}
    
    	#endregion
    }
}
