//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    [System.Data.Services.Common.DataServiceEntity]
    [System.Data.Services.Common.DataServiceKey("FileKey")]
    public partial class FilesWizardInfo : System.IEquatable<FilesWizardInfo>
    {
        public System.Guid FileKey { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is FilesWizardInfo ? Equals(obj as FilesWizardInfo) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ FileKey.GetHashCode();
    			hash = (hash * 16777619) ^ (ClientFirstName == null ? 0 : ClientFirstName.GetHashCode());
    			hash = (hash * 16777619) ^ (ClientLastName == null ? 0 : ClientLastName.GetHashCode());
    			hash = (hash * 16777619) ^ (RunDate == null ? 0 : RunDate.GetHashCode());
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<FilesWizardInfo> Members
    
    	public bool Equals(FilesWizardInfo rhs)
    	{
    		if(rhs == null)
    			return false;
    			
    		return System.Collections.Generic.EqualityComparer<FilesWizardInfo>.Equals(FileKey, rhs.FileKey) && System.Collections.Generic.EqualityComparer<FilesWizardInfo>.Equals(ClientFirstName, rhs.ClientFirstName) && System.Collections.Generic.EqualityComparer<FilesWizardInfo>.Equals(ClientLastName, rhs.ClientLastName) && System.Collections.Generic.EqualityComparer<FilesWizardInfo>.Equals(RunDate, rhs.RunDate);
    	}
    
    	#endregion
    }
}
