//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    [System.Data.Services.Common.DataServiceEntity]
    [System.Data.Services.Common.DataServiceKey("LoginId")]
    public partial class LoginEntry : System.IEquatable<LoginEntry>
    {
        public System.Guid LoginId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime LoginDate { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is LoginEntry ? Equals(obj as LoginEntry) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ LoginId.GetHashCode();
    			hash = (hash * 16777619) ^ UserId.GetHashCode();
    			hash = (hash * 16777619) ^ LoginDate.GetHashCode();
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<LoginEntry> Members
    
    	public bool Equals(LoginEntry rhs)
    	{
    		if(rhs == null)
    			return false;
    			
    		return System.Collections.Generic.EqualityComparer<LoginEntry>.Equals(LoginId, rhs.LoginId) && System.Collections.Generic.EqualityComparer<LoginEntry>.Equals(UserId, rhs.UserId) && System.Collections.Generic.EqualityComparer<LoginEntry>.Equals(LoginDate, rhs.LoginDate);
    	}
    
    	#endregion
    }
}
