//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    [System.Data.Services.Common.DataServiceEntity]
    [System.Data.Services.Common.DataServiceKey("UserId")]
    public partial class User : System.IEquatable<User>
    {
        public User()
        {
            this.Addresses = new HashSet<Address>();
            this.AgentIds = new HashSet<AgentId>();
            this.ContactNumbers = new HashSet<ContactNumber>();
            this.EMailAddresses = new HashSet<EMailAddress>();
            this.Preferences = new HashSet<Preference>();
            this.Websites = new HashSet<Website>();
            this.Badges = new HashSet<Badges>();
            this.Name = new Name();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public System.Guid UsernameId { get; set; }
    
        public Name Name { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<AgentId> AgentIds { get; set; }
        public virtual ICollection<ContactNumber> ContactNumbers { get; set; }
        public virtual ICollection<EMailAddress> EMailAddresses { get; set; }
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<Website> Websites { get; set; }
        public virtual ICollection<Badges> Badges { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is User ? Equals(obj as User) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ UserId.GetHashCode();
    			hash = (hash * 16777619) ^ (Type == null ? 0 : Type.GetHashCode());
    			hash = (hash * 16777619) ^ UsernameId.GetHashCode();
    			hash = (hash * 16777619) ^ (Name == null ? 0 : Name.GetHashCode());
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<User> Members
    
    	public bool Equals(User rhs)
    	{
    		if(rhs == null)
    			return false;
    			
    		return System.Collections.Generic.EqualityComparer<User>.Equals(UserId, rhs.UserId) && System.Collections.Generic.EqualityComparer<User>.Equals(Type, rhs.Type) && System.Collections.Generic.EqualityComparer<User>.Equals(UsernameId, rhs.UsernameId) && System.Collections.Generic.EqualityComparer<User>.Equals(Name, rhs.Name);
    	}
    
    	#endregion
    }
}
