//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace WhippedCream.Data.User
{
    
    public partial class ZipCode
    {
        public string Primary { get; set; }
        public string Secondary { get; set; }
    
    	#region Members overriden from System.Object
    
    	public override bool Equals(object obj)
    	{
    		return obj is ZipCode ? Equals(obj as ZipCode) : false;
    	}
    
    	/// <summary>
    	/// The Implementation of this algorithm was taken
    	/// from [here](http://www.isthe.com/chongo/tech/comp/fnv/).
    	/// </summary>
    	public override int GetHashCode()
    	{
    		int hash = 13;
    		unchecked
    		{
    			hash = (hash * 16777619) ^ (Primary == null ? 0 : Primary.GetHashCode());
    			hash = (hash * 16777619) ^ (Secondary == null ? 0 : Secondary.GetHashCode());
    		}
    		return hash;
    	}
    
    	public override string ToString()
    	{
    		return base.ToString();
    	}
    
    	#endregion
    
    	#region IEquatable<ZipCode> Members
    
    	public bool Equals(ZipCode rhs)
    	{
    		if(rhs == null)
    			return false;
    
    		return System.Collections.Generic.EqualityComparer<ZipCode>.Equals(Primary, rhs.Primary) && System.Collections.Generic.EqualityComparer<ZipCode>.Equals(Secondary, rhs.Secondary);
    	}
    
    	#endregion
    }
}
